.catalog:
  name: "Rancher IPsec"
  version: "v0.0.1"

ipsec:
  network_driver:
    name: Rancher IPsec
    default_network:
      name: ipsec
      host_ports: true
      subnets:
      - network_address: '10.42.0.0/16'
      dns:
      - 169.254.169.250
      dns_search:
      - rancher.internal
    cni_config:
      '10-rancher.conf':
        name: rancher-cni-network
        type: rancher-bridge
        bridge: docker0
        bridgeSubnet: '10.42.0.0/16'
        isDefaultGateway: true
        ipMasq: true
        hairpinMode": true
        ipam:
          type: rancher-cni-ipam
          logToFile: /var/log/rancher-ipam.log
